name: "Get Project Id"
author: 'Tetsuya Mori'
description: 'Get Project Id of GitHub Projects'
branding:
  icon: hash
  color: green
inputs:
  github-token:
    default: ''
    required: true
    description: 'Personal Access Token that with `org:read` is granted.'
  project-owner:
    default: ''
    required: true
    description: 'User/Organization name project contains.'
  project-number:
    default: 0
    required: true
    description: 'The number of the target project.'
outputs:
  project-id:
    description: 'Project Id that can be obtained from a given organization and number'
    value: ${{ steps.get-project-id.outputs.project-id }}
  error:
    description: 'Error message.'
    value: ${{ steps.get-project-id.outputs.error }}
runs:
  using: "composite"
  steps:
    - name: Get Project Id
      uses: actions/github-script@v5
      id: get-project-id
      with:
        result-encoding: string
        github-token: ${{ inputs.github-token }}
        script: |
          const variables = {
            login: '${{ inputs.project-owner }}',
            projectNumber: ${{ inputs.project-number }}
          };
          const query = `
            query($login: String!, $projectNumber: Int!) {
              user(login: $login) {
                projectV2(number: $projectNumber) {
                  id
                }
              }
              organization(login: $login) {
                projectV2(number: $projectNumber) {
                  id
                }
              }
            }
          `;

          var result = {};

          try {
            result = await github.graphql(query, variables);
          } catch (error) {
            if (error.data) {
              result = error.data;
            }
            core.setOutput('error', error.errors.map(v=>v.message).join(","));
          }

          if (result.user && result.user.projectV2) {
            core.setOutput('project-id', result.user.projectV2.id);
            return;
          }
          if (result.organization && result.organization.projectV2) {
            core.setOutput('project-id', result.organization.projectV2.id);
            return;
          }
          return;
